# Generated by Django 5.1.1 on 2024-09-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики"},
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=255, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(verbose_name="Дата выпуска"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="electronics_network.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.CharField(max_length=255, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Задолженность",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="house_number",
            field=models.CharField(max_length=10, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="electronics_network.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("factory", "Завод"),
                    ("retail", "Розничная сеть"),
                    ("entrepreneur", "Индивидуальный предприниматель"),
                ],
                default="retail",
                max_length=20,
                verbose_name="Тип поставщика",
            ),
        ),
    ]
